### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by arjtala** [OneSparse/OneSparse#3]
Hi Michael, this looks like an amazing project. Is there any way I could contribute? Not sure my skills are up to par but I really love the idea and would be delighted to help in any way I can

**Comment by michelp** [comment]
Sorry for the delay!  Certainly contributions would be welcome, there is a lot to do.  There are some internal issues and exposing new features in SuiteSparse 3.1.1 which would require some C coding.  One other problem is TOAST varlena objects the format which stores a matrix in a table, is limited to 1GBish.  Postgres has a "large object" C api that might be the right idea to switch to, or have it be configurable in some way.

**Comment by arjology** [comment]
This sounds exciting , any pointers on how one can get started ?

**Comment by michelp** [comment]
Hi @arjology, SuiteSparse just did a 3.2.0 release, so a task needing work is upgrading to 3.2.0.  No backwards incompatible changes were made, so it should be pretty straightforward.  There are two new binary operators, PAIR and ANY which need to be supported.  PAIR always returns 1, it means "both values are present" and ANY returns either of its inputs, doesn't matter which.
